# Generated by Django 4.0.4 on 2023-03-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrap', '0005_booking_address_booking_date_booking_typeaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='%Y-%m-%d'),
        ),
    ]
